var aaa = {
    test: [
        {"name": "China", "num": "+86"},
        {"name": "Taiwan", "num": "+886"},
        {"name": "Hong Kong", "num": "+852"},
        {"name": "Macau", "num": "+853"},
        {"name": "United States", "num": "+1 "},
        {"name": "Canada", "num": "+1"},
        {"name": "Russia", "num": "+7 "},
        {"name": "Kazakhstan", "num": "+7"},
        {"name": "Egypt", "num": "+20"},
        {"name": "South Africa", "num": "+27"},
        {"name": "Greece", "num": "+30"},
        {"name": "Netherlands", "num": "+31"},
        {"name": "Belgium", "num": "+32"},
        {"name": "France", "num": "+33"},
        {"name": "Spain", "num": "+34"},
        {"name": "Hungary", "num": "+36"},
        {"name": "Italy", "num": "+39"},
        {"name": "Romania", "num": "+40"},
        {"name": "Switzerland", "num": "+41"},
        {"name": "Austria", "num": "+43"},
        {"name": "United Kingdom", "num": "+44"},
        {"name": "Denmark", "num": "+45"},
        {"name": "Sweden", "num": "+46"},
        {"name": "Norway", "num": "+47"},
        {"name": "Poland", "num": "+48"},
        {"name": "Germany", "num": "+49"},
        {"name": "Peru", "num": "+51"},
        {"name": "Mexico", "num": "+52"},
        {"name": "Cuba", "num": "+53"},
        {"name": "Argentina", "num": "+54"},
        {"name": "Brazil", "num": "+55"},
        {"name": "Chile", "num": "+56"},
        {"name": "Colombia", "num": "+57"},
        {"name": "Venezuela", "num": "+58"},
        {"name": "Malaysia", "num": "+60"},
        {"name": "Australia", "num": "+61"},
        {"name": "Indonesia", "num": "+62"},
        {"name": "Philippines", "num": "+63"},
        {"name": "New Zealand", "num": "+64"},
        {"name": "Singapore", "num": "+65"},
        {"name": "Thailand", "num": "+66"},
        {"name": "Japan", "num": "+81"},
        {"name": "South Korea", "num": "+82"},
        {"name": "Vietnam", "num": "+84"},
        {"name": "Turkey", "num": "+90"},
        {"name": "India", "num": "+91"},
        {"name": "Pakistan", "num": "+92"},
        {"name": "Afghanistan", "num": "+93"},
        {"name": "Sri Lanka", "num": "+94"},
        {"name": "Myanmar", "num": "+95"},
        {"name": "Iran", "num": "+98"},
        {"name": "South Sudan", "num": "+211"},
        {"name": "Morocco", "num": "+212"},
        {"name": "Algeria", "num": "+213"},
        {"name": "Tunisia", "num": "+216"},
        {"name": "Libya", "num": "+218"},
        {"name": "Gambia", "num": "+220"},
        {"name": "Senegal", "num": "+221"},
        {"name": "Mauritania", "num": "+222"},
        {"name": "Mali", "num": "+223"},
        {"name": "Guinea", "num": "+224"},
        {"name": "Ivory Coast", "num": "+225"},
        {"name": "Burkina Faso", "num": "+226"},
        {"name": "Niger", "num": "+227"},
        {"name": "Togo", "num": "+228"},
        {"name": "Benin", "num": "+229"},
        {"name": "Mauritius", "num": "+230"},
        {"name": "Liberia", "num": "+231"},
        {"name": "Sierra Leone", "num": "+232"},
        {"name": "Ghana", "num": "+233"},
        {"name": "Nigeria", "num": "+234"},
        {"name": "Chad", "num": "+235"},
        {"name": "Central African Republic", "num": "+236"},
        {"name": "Cameroon", "num": "+237"},
        {"name": "Cape Verde", "num": "+238"},
        {"name": "Sao Tome and Principe", "num": "+239"},
        {"name": "Equatorial Guinea", "num": "+240"},
        {"name": "Gabon", "num": "+241"},
        {"name": "Republic Of The Congo", "num": "+242"},
        {"name": "Democratic Republic of the Congo", "num": "+243"},
        {"name": "Angola", "num": "+244"},
        {"name": "Guinea-Bissau", "num": "+245"},
        {"name": "Ascension Island", "num": "+247"},
        {"name": "Seychelles", "num": "+248"},
        {"name": "Sudan", "num": "+249"},
        {"name": "Rwanda", "num": "+250"},
        {"name": "Ethiopia", "num": "+251"},
        {"name": "Somalia", "num": "+252"},
        {"name": "Djibouti", "num": "+253"},
        {"name": "Kenya", "num": "+254"},
        {"name": "Tanzania", "num": "+255"},
        {"name": "Uganda", "num": "+256"},
        {"name": "Burundi", "num": "+257"},
        {"name": "Mozambique", "num": "+258"},
        {"name": "Zambia", "num": "+260"},
        {"name": "Madagascar", "num": "+261"},
        {"name": "Réunion Island", "num": "+262"},
        {"name": "Zimbabwe", "num": "+263"},
        {"name": "Namibia", "num": "+264"},
        {"name": "Malawi", "num": "+265"},
        {"name": "Lesotho", "num": "+266"},
        {"name": "Botswana", "num": "+267"},
        {"name": "Swaziland", "num": "+268"},
        {"name": "Comoros", "num": "+269"},
        {"name": "Mayotte", "num": "+269"},
        {"name": "Aruba", "num": "+297"},
        {"name": "Faroe Islands", "num": "+298"},
        {"name": "Greenland", "num": "+299"},
        {"name": "Gibraltar", "num": "+350"},
        {"name": "Portugal", "num": "+351"},
        {"name": "Luxembourg", "num": "+352"},
        {"name": "Ireland", "num": "+353"},
        {"name": "Iceland", "num": "+354"},
        {"name": "Albania", "num": "+355"},
        {"name": "Malta", "num": "+356"},
        {"name": "Cyprus", "num": "+357"},
        {"name": "Finland", "num": "+358"},
        {"name": "Bulgaria", "num": "+359"},
        {"name": "Lithuania", "num": "+370"},
        {"name": "Latvia", "num": "+371"},
        {"name": "Estonia", "num": "+372"},
        {"name": "Moldova", "num": "+373"},
        {"name": "Armenia", "num": "+374"},
        {"name": "Belarus", "num": "+375"},
        {"name": "Andorra", "num": "+376"},
        {"name": "Monaco", "num": "+377"},
        {"name": "San Marino", "num": "+378"},
        {"name": "Ukraine", "num": "+380"},
        {"name": "Serbia", "num": "+381"},
        {"name": "Montenegro", "num": "+382"},
        {"name": "Croatia", "num": "+385"},
        {"name": "Slovenia", "num": "+386"},
        {"name": "Bosnia and Herzegovina", "num": "+387"},
        {"name": "Macedonia", "num": "+389"},
        {"name": "Czech Republic", "num": "+420"},
        {"name": "Slovakia", "num": "+421"},
        {"name": "Liechtenstein", "num": "+423"},
        {"name": "Belize", "num": "+501"},
        {"name": "Guatemala", "num": "+502"},
        {"name": "El Salvador", "num": "+503"},
        {"name": "Honduras", "num": "+504"},
        {"name": "Nicaragua", "num": "+505"},
        {"name": "Costa Rica", "num": "+506"},
        {"name": "Panama", "num": "+507"},
        {"name": "Saint Pierre and Miquelon", "num": "+508"},
        {"name": "Haiti", "num": "+509"},
        {"name": "Guadeloupe", "num": "+590"},
        {"name": "Bolivia", "num": "+591"},
        {"name": "Guyana", "num": "+592"},
        {"name": "Ecuador", "num": "+593"},
        {"name": "French Guiana", "num": "+594"},
        {"name": "Paraguay", "num": "+595"},
        {"name": "Martinique", "num": "+596"},
        {"name": "Suriname", "num": "+597"},
        {"name": "Uruguay", "num": "+598"},
        {"name": "Curacao", "num": "+599"},
        {"name": "Bonaire, Sint Eustatius and Saba", "num": "+599"},
        {"name": "East Timor", "num": "+670"},
        {"name": "Brunei", "num": "+673"},
        {"name": "Papua New Guinea", "num": "+675"},
        {"name": "Tonga", "num": "+676"},
        {"name": "Solomon Islands", "num": "+677"},
        {"name": "Vanuatu", "num": "+678"},
        {"name": "Fiji", "num": "+679"},
        {"name": "Palau", "num": "+680"},
        {"name": "Cook Islands", "num": "+682"},
        {"name": "Samoa", "num": "+685"},
        {"name": "Kiribati", "num": "+686"},
        {"name": "New Caledonia", "num": "+687"},
        {"name": "French Polynesia", "num": "+689"},
        {"name": "Cambodia", "num": "+855"},
        {"name": "Laos", "num": "+856"},
        {"name": "Bangladesh", "num": "+880"},
        {"name": "Maldives", "num": "+960"},
        {"name": "Lebanon", "num": "+961"},
        {"name": "Jordan", "num": "+962"},
        {"name": "Syria", "num": "+963"},
        {"name": "Iraq", "num": "+964"},
        {"name": "Kuwait", "num": "+965"},
        {"name": "Saudi Arabia", "num": "+966"},
        {"name": "Yemen", "num": "+967"},
        {"name": "Oman", "num": "+968"},
        {"name": "Palestinian Territory", "num": "+970"},
        {"name": "United Arab Emirates", "num": "+971"},
        {"name": "Israel", "num": "+972"},
        {"name": "Bahrain", "num": "+973"},
        {"name": "Qatar", "num": "+974"},
        {"name": "Bhutan", "num": "+975"},
        {"name": "Mongolia", "num": "+976"},
        {"name": "Nepal", "num": "+977"},
        {"name": "Tajikistan", "num": "+992"},
        {"name": "Turkmenistan", "num": "+993"},
        {"name": "Azerbaijan", "num": "+994"},
        {"name": "Georgia", "num": "+995"},
        {"name": "Kyrgyzstan", "num": "+996"},
        {"name": "Uzbekistan", "num": "+998"},
        {"name": "Bahamas", "num": "+1242"},
        {"name": "Barbados", "num": "+1246"},
        {"name": "Anguilla", "num": "+1264"},
        {"name": "Antigua and Barbuda", "num": "+1268"},
        {"name": "Virgin Islands, US", "num": "+1284"},
        {"name": "Virgin Islands, British", "num": "+1340"},
        {"name": "Cayman Islands", "num": "+1345"},
        {"name": "Bermuda", "num": "+1441"},
        {"name": "Grenada", "num": "+1473"},
        {"name": "Turks and Caicos Islands", "num": "+1649"},
        {"name": "Montserrat", "num": "+1664"},
        {"name": "Guam", "num": "+1671"},
        {"name": "American Samoa", "num": "+1684"},
        {"name": "Sint Maarten (Dutch Part)", "num": "+1721"},
        {"name": "Saint Lucia", "num": "+1758"},
        {"name": "Dominica", "num": "+1767"},
        {"name": "Saint Vincent and The Grenadines", "num": "+1784"},
        {"name": "Puerto Rico", "num": "+1787"},
        {"name": "Dominican Republic", "num": "+1809"},
        {"name": "Trinidad and Tobago", "num": "+1868"},
        {"name": "Saint Kitts and Nevis", "num": "+1869"},
        {"name": "Jamaica", "num": "+1876"}
    ]
};


var path = require('path');

var bb = aaa.test.map(d => {
    var text = `<span class="piece-a">${d.name}</span><span class="piece-b">${d.num}</span>`;
    return d.num
});


var {writeFilePrms} = require('./utils/fsPrms');

writeFilePrms(path.resolve(__dirname, './test.json'), JSON.stringify(bb));

